apiVersion: 1

policies:
  - orgId: 1
    receiver: telegram-quant-ops
    group_by:
      - alertname
      - job
      - scope
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes: []
