#!/usr/bin/env python3
"""Generate a features.yaml with all available factors from feature_dependencies.yaml.

This script reads feature_dependencies.yaml and generates a features.yaml that includes
all output columns from all features, suitable for factor evaluation and iterative selection.
"""

import sys
from pathlib import Path
import yaml

# Add project root to path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.features.loader.strategy_feature_loader import StrategyFeatureLoader


def generate_all_features_yaml(
    strategy_config_path: Path,
    output_path: Path | None = None,
) -> Path:
    """Generate features.yaml with all available factors.

    Args:
        strategy_config_path: Path to strategy config directory (e.g., config/strategies/sr_reversal_long)
        output_path: Optional output path. If None, will write to strategy_config_path/features_all.yaml

    Returns:
        Path to generated YAML file
    """
    strategy_config_path = Path(strategy_config_path)
    if not strategy_config_path.exists():
        raise FileNotFoundError(
            f"Strategy config path not found: {strategy_config_path}"
        )

    # Load feature dependencies
    feature_loader = StrategyFeatureLoader()
    features_config = feature_loader.feature_deps.get("features", {})

    # Collect all feature names (not output columns, as those are automatically resolved)
    # We only need feature compute function names (with _f suffix) for dependency resolution
    all_feature_names = set()
    for feature_name in features_config.keys():
        # Only include feature compute function names (with _f suffix)
        if feature_name.endswith("_f"):
            all_feature_names.add(feature_name)

    # Resolve all dependencies recursively to ensure features_all.yaml is self-contained
    # This ensures that if a feature depends on another feature, the dependency is also included
    all_requested_with_deps = feature_loader.resolve_dependencies(
        list(all_feature_names)
    )

    # Convert to set and sort for consistent output
    all_requested = set(all_requested_with_deps)

    # Load base strategy config to preserve other settings
    base_features_path = strategy_config_path / "features.yaml"
    base_config = {}
    if base_features_path.exists():
        try:
            with open(base_features_path, "r", encoding="utf-8") as f:
                base_config = yaml.safe_load(f) or {}
        except Exception as e:
            print(f"⚠️  Could not load base features.yaml: {e}")

    # Build features.yaml structure
    features_config_yaml = {
        "name": base_config.get("name", strategy_config_path.name),
        "description": base_config.get(
            "description",
            f"Feature pipeline with ALL available factors from feature_dependencies.yaml. "
            f"Use this as a starting point for factor evaluation and iterative selection.",
        ),
        "feature_pipeline": {
            "requested_features": sorted(all_requested),
            "ensure_signal_column": base_config.get("feature_pipeline", {}).get(
                "ensure_signal_column",
                {"name": "signal", "default_value": 0},
            ),
        },
        "notes": f"""
This configuration includes ALL features from feature_dependencies.yaml with all dependencies resolved.

Usage:
1. Use this as input to factor-eval to evaluate all factors
2. Review the evaluation results and use the generated features_pool_b.yaml
3. Use feature-group-search to find optimal feature combinations

Total features in feature_dependencies.yaml: {len(features_config)}
Total requested features (with dependencies): {len(all_requested)}

Note: This is self-contained - all dependencies are automatically resolved and included.
When using this file with factor-eval, it will work independently without needing features.yaml.

Generated by: scripts/generate_all_features_yaml.py
        """.strip(),
    }

    # Determine output path
    if output_path is None:
        output_path = strategy_config_path / "features_all.yaml"
    else:
        output_path = Path(output_path)

    # Write YAML file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        yaml.dump(
            features_config_yaml,
            f,
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=False,
        )

    print(
        f"✅ Generated features_all.yaml with {len(all_requested)} features (self-contained with all dependencies)"
    )
    print(f"   Output: {output_path}")
    print(f"   Total features in feature_dependencies.yaml: {len(features_config)}")
    print(
        f"   Total requested features (with dependencies resolved): {len(all_requested)}"
    )
    print(
        f"   Note: This file is self-contained and can be used independently with factor-eval"
    )

    return output_path


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate features.yaml with all available factors"
    )
    parser.add_argument(
        "--strategy-config",
        required=True,
        help="Path to strategy config directory (e.g., config/strategies/sr_reversal_long)",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output path (default: {strategy_config}/features_all.yaml)",
    )

    args = parser.parse_args()

    generate_all_features_yaml(
        strategy_config_path=args.strategy_config,
        output_path=args.output,
    )
