#!/usr/bin/env python3
"""Generate a features.yaml with all available factors from feature_dependencies.yaml.

This script reads feature_dependencies.yaml and generates a features.yaml that includes
all output columns from all features, suitable for factor evaluation and iterative selection.
"""

import sys
from pathlib import Path
import yaml

# Add project root to path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.features.loader.strategy_feature_loader import StrategyFeatureLoader


def generate_all_features_yaml(
    strategy_config_path: Path,
    output_path: Path | None = None,
) -> Path:
    """Generate features.yaml with all available factors.

    Args:
        strategy_config_path: Path to strategy config directory (e.g., config/strategies/sr_reversal_long)
        output_path: Optional output path. If None, will write to strategy_config_path/features_all.yaml

    Returns:
        Path to generated YAML file
    """
    strategy_config_path = Path(strategy_config_path)
    if not strategy_config_path.exists():
        raise FileNotFoundError(
            f"Strategy config path not found: {strategy_config_path}"
        )

    # Load feature dependencies
    feature_loader = StrategyFeatureLoader()
    features_config = feature_loader.feature_deps.get("features", {})

    # Collect both feature names AND their output columns
    # This ensures dependency resolution works correctly
    all_requested = set()
    feature_to_columns = {}

    for feature_name, feature_info in features_config.items():
        output_cols = feature_info.get("output_columns", [])
        # Add the feature name itself (for dependency resolution)
        all_requested.add(feature_name)
        # Also add all output columns (for direct column access)
        if output_cols:
            all_requested.update(output_cols)
            feature_to_columns[feature_name] = output_cols

    # Load base strategy config to preserve other settings
    base_features_path = strategy_config_path / "features.yaml"
    base_config = {}
    if base_features_path.exists():
        try:
            with open(base_features_path, "r", encoding="utf-8") as f:
                base_config = yaml.safe_load(f) or {}
        except Exception as e:
            print(f"⚠️  Could not load base features.yaml: {e}")

    # Build features.yaml structure
    features_config_yaml = {
        "name": base_config.get("name", strategy_config_path.name),
        "description": base_config.get(
            "description",
            f"Feature pipeline with ALL available factors from feature_dependencies.yaml. "
            f"Use this as a starting point for factor evaluation and iterative selection.",
        ),
        "feature_pipeline": {
            "requested_features": sorted(all_requested),
            "ensure_signal_column": base_config.get("feature_pipeline", {}).get(
                "ensure_signal_column",
                {"name": "signal", "default_value": 0},
            ),
        },
        "notes": f"""
This configuration includes ALL features AND their output columns from feature_dependencies.yaml.

Usage:
1. Use this as input to ts-factor-eval to evaluate all factors
2. Review the evaluation results and use the generated features_suggested.yaml
3. Iteratively refine your factor selection based on IC/Sharpe metrics

Total features: {len(features_config)}
Total requested items (features + output columns): {len(all_requested)}

Note: This includes both feature names (for dependency resolution) and output columns (for direct access).
This ensures all dependencies are properly resolved.

Generated by: scripts/generate_all_features_yaml.py
        """.strip(),
    }

    # Determine output path
    if output_path is None:
        output_path = strategy_config_path / "features_all.yaml"
    else:
        output_path = Path(output_path)

    # Write YAML file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        yaml.dump(
            features_config_yaml,
            f,
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=False,
        )

    print(
        f"✅ Generated features_all.yaml with {len(all_requested)} items (features + output columns)"
    )
    print(f"   Output: {output_path}")
    print(f"   Total features: {len(features_config)}")
    print(f"   Total requested items: {len(all_requested)}")

    return output_path


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate features.yaml with all available factors"
    )
    parser.add_argument(
        "--strategy-config",
        required=True,
        help="Path to strategy config directory (e.g., config/strategies/sr_reversal_long)",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output path (default: {strategy_config}/features_all.yaml)",
    )

    args = parser.parse_args()

    generate_all_features_yaml(
        strategy_config_path=args.strategy_config,
        output_path=args.output,
    )
