-- Machine-readable DDL is split intentionally:
--
-- • Trend / PCM classical storage (OrderManager): schema_trend.sql
-- • Multi-leg runs (MultiLegStorage): schema_multi_leg.sql
--
-- Do not revive a monolithic executescript here — both halves used to CREATE the
-- full union in whichever db_path was opened, mixing table families.
